default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: Postgres

development:
  <<: *default
  database: calendar_dev

test:
  <<: *default
  database: calendar_test

production:
  <<: *default
  database: calendar_production
  username: postgres
  password: <%= ENV['CALENDAR_DATABASE_PASSWORD'] %>